### PR TITLE
Use menuBarFontSize and offset of 1 to match.

### LINKED ISSUE #92: Match font family and size to system font
Currently the font is smaller, and maybe a different style, I don't know.

screenshot

Also, the icon seems to be not vertically aligned properly, and it's one or two pixels down.

Thanks!

### PR DESCRIPTION
**Pull request by JakeWharton**
Closes #92.

screen shot 2015-12-02 at 1 26 19 am

### CODE REVIEW

**Comment by JakeWharton** [comment]
Sorry in the screenshot I show a different battery icon alignment than normal. I'm going to make this a separate PR. Focus only on the font.

**Comment by codler** [comment]
Thanks for the pr! ill take a look soon

**Comment by nbppp2** [comment]
For MacOS sierra it appears that this needs to be changed to 
`NSDictionary *attributedStyle = @{NSFontAttributeName: [NSFont menuBarFontOfSize:0], NSBaselineOffsetAttributeName: @(0)};`

screen shot 2016-09-23 at 2 46 57 pm

**Comment by panr** [comment]
icon-position

Any chance to fix icon alignment soon on Sierra? 😔

**Comment by jsteweii** [comment]
how is this progressing, and what the last poster said too. Theres no banner notifications also.

Best regards,

jsteweii.

**Comment by jsteweii** [comment]
Bump Man, I've paid for this app in App Store and almost a year with no activity from your side. That is bad customer care.

**Comment by jsteweii** [comment]
Is this a dead project? If so, please just let us all know Dev, then I won't waste anymore time here. I think it's a shame, because it really does what I would like it to do. I also think that you should pull it from the App Store, so that no one else pays for a product that isn't finished. It kind of pisses me off that you aren't responding at all since I've paid for your product. But hey, money is money right?!

**Pull request closed without merging**
